/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "employess.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Lora_telemetry, Lora_telemetry, AUTO)


PB_BIND(Lora_info, Lora_info, AUTO)


PB_BIND(Lora, Lora, AUTO)


PB_BIND(Loras, Loras, AUTO)



