/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_EMPLOYESS_PB_H_INCLUDED
#define PB_EMPLOYESS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Lora_telemetry {
    float temperature; /* V1: Nhiệt độ không khí (°C) */
    float humidity; /* V2: Độ ẩm không khí (% RH) */
    float soil_moisture; /* V3: Độ ẩm đất (% hoặc raw) */
    float soil_temperature; /* V4: Nhiệt độ đất (°C) */
    float ph_level; /* V5: Độ pH đất hoặc nước */
    float ec_level; /* V6: Độ dẫn điện EC (µS/cm) */
    float light_intensity; /* V7: Cường độ ánh sáng (lux hoặc raw) */
    float co2_level; /* V8: Nồng độ CO2 (ppm) */
    float rainfall_level; /* V9: Lượng mưa (mm) */
    float leaf_wetness; /* V10: Độ ẩm lá cây (% hoặc binary) */
} Lora_telemetry;

typedef struct _Lora_info {
    pb_callback_t deviceName;
    pb_callback_t addrHigh;
    pb_callback_t addrLow;
    uint32_t id;
} Lora_info;

typedef struct _Lora {
    bool has_info;
    Lora_info info;
    bool has_telemetry;
    Lora_telemetry telemetry;
} Lora;

typedef struct _Loras {
    pb_callback_t list_lora;
} Loras;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Lora_telemetry_init_default              {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Lora_info_init_default                   {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define Lora_init_default                        {false, Lora_info_init_default, false, Lora_telemetry_init_default}
#define Loras_init_default                       {{{NULL}, NULL}}
#define Lora_telemetry_init_zero                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Lora_info_init_zero                      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define Lora_init_zero                           {false, Lora_info_init_zero, false, Lora_telemetry_init_zero}
#define Loras_init_zero                          {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Lora_telemetry_temperature_tag           1
#define Lora_telemetry_humidity_tag              2
#define Lora_telemetry_soil_moisture_tag         3
#define Lora_telemetry_soil_temperature_tag      4
#define Lora_telemetry_ph_level_tag              5
#define Lora_telemetry_ec_level_tag              6
#define Lora_telemetry_light_intensity_tag       7
#define Lora_telemetry_co2_level_tag             8
#define Lora_telemetry_rainfall_level_tag        9
#define Lora_telemetry_leaf_wetness_tag          10
#define Lora_info_deviceName_tag                 1
#define Lora_info_addrHigh_tag                   2
#define Lora_info_addrLow_tag                    3
#define Lora_info_id_tag                         4
#define Lora_info_tag                            1
#define Lora_telemetry_tag                       2
#define Loras_list_lora_tag                      1

/* Struct field encoding specification for nanopb */
#define Lora_telemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    soil_moisture,     3) \
X(a, STATIC,   SINGULAR, FLOAT,    soil_temperature,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    ph_level,          5) \
X(a, STATIC,   SINGULAR, FLOAT,    ec_level,          6) \
X(a, STATIC,   SINGULAR, FLOAT,    light_intensity,   7) \
X(a, STATIC,   SINGULAR, FLOAT,    co2_level,         8) \
X(a, STATIC,   SINGULAR, FLOAT,    rainfall_level,    9) \
X(a, STATIC,   SINGULAR, FLOAT,    leaf_wetness,     10)
#define Lora_telemetry_CALLBACK NULL
#define Lora_telemetry_DEFAULT NULL

#define Lora_info_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   deviceName,        1) \
X(a, CALLBACK, SINGULAR, BYTES,    addrHigh,          2) \
X(a, CALLBACK, SINGULAR, BYTES,    addrLow,           3) \
X(a, STATIC,   SINGULAR, UINT32,   id,                4)
#define Lora_info_CALLBACK pb_default_field_callback
#define Lora_info_DEFAULT NULL

#define Lora_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  info,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  telemetry,         2)
#define Lora_CALLBACK NULL
#define Lora_DEFAULT NULL
#define Lora_info_MSGTYPE Lora_info
#define Lora_telemetry_MSGTYPE Lora_telemetry

#define Loras_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  list_lora,         1)
#define Loras_CALLBACK pb_default_field_callback
#define Loras_DEFAULT NULL
#define Loras_list_lora_MSGTYPE Lora

extern const pb_msgdesc_t Lora_telemetry_msg;
extern const pb_msgdesc_t Lora_info_msg;
extern const pb_msgdesc_t Lora_msg;
extern const pb_msgdesc_t Loras_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Lora_telemetry_fields &Lora_telemetry_msg
#define Lora_info_fields &Lora_info_msg
#define Lora_fields &Lora_msg
#define Loras_fields &Loras_msg

/* Maximum encoded size of messages (where known) */
/* Lora_info_size depends on runtime parameters */
/* Lora_size depends on runtime parameters */
/* Loras_size depends on runtime parameters */
#define EMPLOYESS_PB_H_MAX_SIZE                  Lora_telemetry_size
#define Lora_telemetry_size                      50

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
